name: ci

on: [pull_request, push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - name: build
        run: make

      - name: run
        run: target/sip_test
